version: "2.2"
services:
  notificationservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: node index.js
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    healthcheck:
      test: [ 'CMD', 'rabbitmq-diagnostics', '-q', 'status' ]
      timeout: 5s
      retries: 5
    restart: on-failure
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
