# Stage 1 - the build process
FROM node:18-alpine as build-deps

WORKDIR /app

COPY . .
RUN npm ci
RUN npm run build

RUN npx -c 'echo SERVICE_NAME="$npm_package_name"' >> .env
RUN npx -c 'echo SERVICE_VERSION="$npm_package_version"' >> .env

## Stage 2 - the production environment
FROM node:18-alpine

WORKDIR /app

COPY --from=build-deps /app/dist .
COPY --from=build-deps /app/package*.json .

RUN npm ci --omit=dev

EXPOSE 8080

CMD ["node", "./index.js"]
